development:
  root: https://localhost:9292
  openid_root: https://openid.example.com
  this_server: primary.example.com
  cookie_domain: ".example.com"
  stats:
    server: https://stats.example.com
    token: "000000"
  session_secret: "PUT SOMETHING HERE"
  jwt_key: "PUT SOMETHING HERE"
  ga_id: UA-XXXXXXXX
  credit: <a href="http://indiewebcamp.com/sponsors">sponsors</a> of IndieWebCamp events
  redis:
    host: redis_db # This should be the name of the redis docker container from docker-compose
    port: 6379
  mailgun:
    api_key: xxx
    domain: mail.example.com
    from: "login@indieauth.com"
  providers:
    flickr:
      client_id: 
      client_secret: 
    github:
      client_id: 
      client_secret: 
    google_oauth2:
      client_id: 
      client_secret: 
    twitter:
      client_id: 
      client_secret: 
    lastfm:
      client_id: 
      client_secret: 
    beeminder:
      client_id: 
      client_secret: 
    eventbrite:
      client_id: 
      client_secret: 
